config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  resources :posts, except: [:show] do
    resources :comments, only: [:new, :create]
    resources :likes, only: [:new, :create]
    post :download, on: :member
  end

  resources :comments, only: [:destroy]
  resources :likes, only: [:destroy]

  resources :users, only: [:show] do
    collection do
      get "all"
    end
  end

  get 'info', to: 'pages#info'
  get 'all_users', to: 'pages#all_users'
  get 'seen_pwa', to: 'pages#seen_pwa'
  get 'toggle_dark_mode', to: 'pages#toggle_dark_mode'
  get 'no_user', to: 'users#no_user'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  validates :first_name, presence: :true
  validates :last_name, presence: :true
  # validates :username, uniqueness: true
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :avatar
  extend FriendlyId
  friendly_id :user_username, use: :slugged
  include PgSearch
  pg_search_scope :search_by_name,
                  against: [:first_name, :last_name, :username],
                  using: {
                    tsearch: { prefix: true }
                  }

  def user_username
    username.present? ? username : "#{first_name}-#{last_name}"
  end

  def initials
    "#{first_name.first.upcase}#{last_name.first.upcase}"
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def should_generate_new_friendly_id?
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :first_time_visit, unless: -> { cookies[:not_first_visit] }
  before_action :dark_mode
  add_flash_types :success, :danger
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, :avatar])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  def first_time_visit
    @first_visit = true
  end

  def dark_mode
    cookies[:dark_mode] == "true" ? @dark_mode = true : @dark_mode = false
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.post = @post
    render partial: 'posts/modal_comment', locals: { comment: @comment } if @comment.save
    authorize @comment
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@comment.post)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = Like.new(post: @post, user: current_user)
    if @like.save
      render partial: 'posts/post_user', locals: { post: @post }
    else
      redirect_to posts_path, alert: 'Something went wrong'
    end
    authorize @like
  end

  def destroy
    @like = Like.find(params[:id])
    @like.destroy
    authorize @like
    render partial: 'posts/post_user', locals: { post: @like.post }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :info, :seen_pwa, :toggle_dark_mode]

  def home
    @post = Post.new
    redirect_to posts_path if user_signed_in?
  end

  def info
  end

  def seen_pwa
    cookies.permanent[:not_first_visit] = true
  end

  def toggle_dark_mode
    @dark_mode == true ? cookies.permanent[:dark_mode] = false : cookies.permanent[:dark_mode] = true
    redirect_to request.referrer
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :download]

  def index
    @posts = policy_scope(Post).order(created_at: :desc)
    # @posts = policy_scope(Post).where.not(user: current_user)
    @comment = Comment.new
  end

  def show
    authorize @post
  end

  def new
    @post = Post.new
    authorize @post
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:success] = "Post created!"
      redirect_to posts_path
    else
      render :new
    end
    authorize @post
  end

  def edit
    authorize @post
  end

  def update
    @post.update(post_params)
    redirect_to post_path(@post)
    authorize @post
  end

  def destroy
    @post.destroy
    flash[:danger] = "Post deleted!"
    redirect_to params[:show].present? ? posts_path : user_path(@post.user)
    authorize @post
  end

  def download
    authorize @post
    attachment_name = @post.photo.blob.filename.to_s
    attachment_url = @post.photo.service_url(secure: true)
    content_type = attachment_name.split('.').last
    file = Down.download(attachment_url)

    send_file(
      file,
      filename: attachment_name,
      type: content_type
    )
  rescue Down::NotFound => e
    p e
    redirect_to posts_path, alert: "Couldn't download post"
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:caption, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.friendly.find(params[:id])
    @not_me = current_user != @user
    @my_posts = Post.where(user: @user).order(created_at: :desc)
    authorize @user
  end

  def all
    @users = User.all.sort_by { |u| (u.posts.count + u.likes.count + u.comments.count) }.reverse
    authorize current_user
  end

  def no_user
    redirect_to user_path(current_user)
    authorize current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_video?(content)
    content.content_type.split('/')[0] == 'video'
  end

  def is_photo?(content)
    content.content_type.split('/')[0] == 'image'
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/posts/_post_user.html.erb
<div class="post-card-user">
  <% if post.likes&.map(&:user).include?(current_user) %>
    <%= link_to like_path(Like.where(user: current_user, post: post).first), remote: true, id: "like-toggle_#{post.id}", data: { action: "ajax:success->posts#toggleLike" }, method: :delete do %>
      <%= image_tag "#{ @dark_mode ? 'post-card-heart-lime.png' : 'post-card-heart-black.png' }", class: 'post-card-heart' %>
    <% end %>
  <% else %>
    <%= link_to post_likes_path(post), remote: true, id: "like-toggle_#{post.id}", data: { action: "ajax:success->posts#toggleLike" }, method: :post do %>
      <%= image_tag "#{ @dark_mode ? 'post-card-heart-white.png' : 'post-card-heart.png' }", class: 'post-card-heart' %>
    <% end %>
  <% end %>
</div>
<div class="number-of-likes">
  <% if post.likes.count == 0 %>
    <p class="boldest m-0 <%= @dark_mode ? 'white' : 'black' %>"><%= pluralize(post.likes.count, 'like') %></p>
  <% elsif post.likes.count == 1 %>
    <span class="d-flex align-items-center" style="margin-right: 4px;">
      <% if post.likes.first.user.avatar.attached? %>
        <%= cl_image_tag post.likes.first.user.avatar.key, format: :jpg, width: 40, class: 'avatar-mini' %>
      <% else %>
        <%= render 'users/user_avatar', user: post.likes.first.user, classes: 'avatar-mini-default' %>
      <% end %>
    </span>
    <p class="boldest m-0 <%= @dark_mode ? 'white' : 'black' %>">
      Liked by <%= link_to post.likes.first.user.user_username, user_path(post.likes.first.user), class: "no-decoration" %>
    </p>
  <% elsif post.likes.count == 2 %>
    <span class="d-flex align-items-center" style="margin-right: -4px;">
      <% post.likes.each_with_index do |l, index| %>
        <% if l.user.avatar.attached? %>
          <%= cl_image_tag l.user.avatar.key, format: :jpg, width: 40, class: "avatar-mini avatar-mini-bordered #{ 'left-sm' if index == 1 }" %>
        <% else %>
          <%= render 'users/user_avatar', user: l.user, classes: "avatar-mini-default #{ 'left-sm' if index == 1 }" %>
        <% end %>
      <% end %>
    </span>
    <p class="boldest m-0 <%= @dark_mode ? 'white' : 'black' %> ">
      Liked by <%= link_to post.likes.first.user.user_username, user_path(post.likes.first.user), class: "no-decoration" %> and <span class="cursor-pointer" data-action="click->posts#showLikes" data-id="<%= post.id %>"><%= pluralize(post.likes.count - 1, 'other') %></span>
    </p>
  <% else %>
    <span class="d-flex align-items-center" style="margin-right: -16px;">
      <% post.likes.first(3).each_with_index do |l, index| %>
        <% if l.user.avatar.attached? %>
          <%= cl_image_tag l.user.avatar.key, format: :jpg, width: 40, class: "avatar-mini avatar-mini-bordered #{ 'left-sm' if index == 1 } #{ 'left-lg' if index == 2 }" %>
        <% else %>
          <%= render 'users/user_avatar', user: l.user, classes: "avatar-mini-default #{ 'left-sm' if index == 1 } #{ 'left-lg' if index == 2 }" %>
        <% end %>
      <% end %>
    </span>
    <p class="boldest m-0 <%= @dark_mode ? 'white' : 'black' %> ">
      Liked by <%= link_to post.likes.first.user.user_username, user_path(post.likes.first.user), class: "no-decoration" %> and <span class="cursor-pointer" data-action="click->posts#showLikes" data-id="<%= post.id %>"><%= pluralize(post.likes.count - 1, 'other') %></span>
    </p>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <h1 class="boldest text-center mt-5 mb-4 <%= @dark_mode ? 'grey' : 'black' %>">Edit Post</h1>
  <%= simple_form_for @post do |f| %>
    <%= f.input :caption, label: false, placeholder: 'Caption', input_html: { class: "devise-input #{ @dark_mode ? 'dark-mode white' : 'normal-mode' }" } %>
    <%= f.submit 'Update Post', class: 'primary-button', data: { action: 'click->common#showLoader' } %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="posts-container d-flex justify-content-center" data-controller="posts">
  <div class="post-index-left mr-3 mb-3">
    <div class="post-sticky">
      <div class="post-index-user p-3 mb-3 <%= @dark_mode ? 'post-border-dark' : 'post-border-normal' %>">
        <div class="post-card-user-info boldest mb-2 d-flex align-items-center">
          <%= render 'users/user_avatar', user: current_user, classes: 'post-card-avatar default-avatar text-28' %>
          <%= link_to user_path(current_user), class: 'no-decoration' do %>
            <span class="ml-2 link-hover <%= @dark_mode ? 'white' : 'black' %>"><%= current_user.user_username %></span>
          <% end %>
        </div>
        <%= link_to "New Post", new_post_path, class: "outline-button small-text mr-1 #{ @dark_mode ? 'white border-grey' : 'black' }" %>
      </div>
    </div>
  </div>
  <div class="post-index-posts">
    <% if @posts.empty? %>
      <div class="d-flex flex-column align-items-center">
        <p class="pt-5 <%= @dark_mode ? 'white' : 'black' %>">No posts yet. Be the first to post!</p>
        <%= link_to "New post", new_post_path, class: "outline-button small-text mr-1 #{ @dark_mode ? 'white border-grey' : 'black' }" %>
      </div>
    <% end %>
    <% @posts.each do |post| %>
      <div class="post-card <%= @dark_mode ? 'post-border-dark' : 'post-border-normal' %>">
        <div class="post-card-user-info boldest d-flex align-items-center justify-content-between user-info <%= 'video-behind' if is_video?(post.photo) %>">
          <%= link_to user_path(post.user), class: 'no-decoration' do %>
            <div class="">
            <% if post.user.avatar.attached? %>
              <%= cl_image_tag post.user.avatar.key, width: 40, format: :jpg, class: 'post-card-avatar' %>
            <% else %>
              <%= render 'users/user_avatar', user: post.user, classes: 'post-card-avatar default-avatar text-20' %>
            <% end %>
            <span class="link-hover <%= @dark_mode ? 'white' : 'black' %>"><%= post.user.user_username %></span>
            </div>
          <% end %>
            <div class="dropdown">
              <i class="fas fa-ellipsis-h <%= @dark_mode ? 'white' : 'black' %> mr-1 pr-2 dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
              <div class="dropdown-menu dropdown-menu-right <%= 'post-border-dark drop-bg' if @dark_mode %>" aria-labelledby="dropdownMenuButton">
                <% if policy(post).destroy? %>
                  <%= link_to "Delete", post_path(post, show: true), method: :delete, class: "dropdown-item #{ @dark_mode ? 'white' : 'black' }", data: { confirm: "Are you sure you want to delete this post?" } %>
                <% end %>
                <%= link_to 'Download', download_post_path(post), method: :post, class: "dropdown-item #{ @dark_mode ? 'white' : 'black' }", target: :blank %>
              </div>
            </div>
        </div>
        <% if post.photo.attached? %>
          <div class="post-card-image">
              <div class="post-like-overlay" data-action="click->posts#showLikeToggle"></div>
              <div class="post-like-toggle" data-action="click->posts#doubleClickToggleLike" data-id="<%= post.id %>"></div>
            <% if post.photo.content_type.split("/")[0] == "image" %>
              <%= cl_image_tag post.photo.key, width: 500, format: :jpg, data: { target: "posts.image" }, class: 'post-image' %>
            <% elsif post.photo.content_type.split("/")[0] == "video" %>
              <div class="video">
                <%= cl_video_tag post.photo.key, width: 500, autoplay: true, quality: :auto , playsinline: true, loop: true, muted: true, data: { target: "posts.video" }, class: 'post-image post-video' %>
              </div>
              <div class="volume" data-action="click->posts#toggleMute">
                <%= image_tag 'volume-on.png', class: 'd-none', width: 14, data: { target: 'posts.volumeOn'} %>
                <%= image_tag 'volume-off.png', width: 14, data: { target: 'posts.volumeOff'} %>
              </div>
            <% end %>
            <div class="white-heart">
              <%= image_tag 'white-heart.png', data: { target: 'heart'}, class: "mr-2" %>
            </div>
          </div>
        <% end %>
        <div class="post-card-content">
          <div class="post-user" data-target="posts.postCard">
            <%= render 'post_user', post: post %>
          </div>
          <% if post.caption.present? %>
            <%= link_to user_path(post.user), class: 'no-decoration' do %>
              <div class="post-card-user-info boldest py-1">
                <% if post.user.avatar.attached? %>
                  <%= cl_image_tag post.user.avatar.key, format: :jpg, width: 40, class: 'avatar-sm' %>
                <% else %>
                  <%= render 'users/user_avatar', user: post.user, classes: 'avatar-sm default-comment-avatar' %>
                <% end %>
                <span class="m-0 link-hover <%= @dark_mode ? 'white' : 'black' %>"><%= post.user.user_username %></span> <span class="s-medium-text <%= @dark_mode ? 'white' : 'black' %>" style="font-weight: 200;"><%= post.caption %></span>
              </div>
            <% end %>
          <% end %>
          <div class="post-comments post-comments-box_<%= post.id %>" data-target="posts.commentsBox">
            <% if post.comments.count > 5 %>
              <p class="text-12 bold m-0 grey cursor-pointer post-modal_<%= post.id %>" data-action="click->posts#showComments" data-id="<%= post.id %>" data-count="<%= post.comments.count %>">view all <%= post.comments.count %> comments</span></p>
            <% else %>
              <% post.comments.each do |comment| %>
                <%= render 'modal_comment', comment: comment %>
              <% end %>
            <% end %>
          </div>
          <p class="text-12 grey" style="margin-bottom: 10px"><%= time_ago_in_words(post.created_at) %> ago</p>
        </div>
        <%= simple_form_for [post, @comment], remote: true, data: { action: "ajax:success->posts#newComment", id: "#{post.id}" } do |f| %>
          <%= f.input :content,
                      required: true,
                      label: false,
                      placeholder: 'Add a comment...',
                      input_html: { class: "post-card-form-input  #{ @dark_mode ? 'dark-mode border-grey white' : 'normal-mode' }", data: { action: "keyup->posts#postButton" } } %>
          <%= f.submit 'Post', class: "post-card-form-button #{ @dark_mode ? 'dark-mode border-grey grey' : 'normal-mode' }", data: { target: 'posts.button' } %>
        <% end %>
      </div>

      <!-- LIKES MODAL -->
      <!-- LIKES MODAL -->
      <!-- LIKES MODAL -->
      <!-- LIKES MODAL -->
      <!-- LIKES MODAL -->

      <div id="likesOffcanvas<%= post.id %>" class="offcanvas offcanvas-bg" data-target="posts.offCanvas">
        <!-- OFFCANVAS UNDERLAY -->
        <div class="underlay" data-action="click->posts#hideOffcanvas" data-target="posts.underlay"></div>
        <!-- OFFCANVAS UNDERLAY -->
        <div class="offcanvas__container justify-content-start offcanvas-bg offcanvas__container-likes">
          <div class="border-bottom pb-3 offcanvas-header">
            <div class="cursor-pointer" data-action="click->posts#hideOffcanvasFromX" data-confirm="You will lose unsaved changes if you continue">
              <%= image_tag "#{ @dark_mode ? 'plus-white.png' : 'plus.png' }", width: 25, class: 'post-exit' %>
            </div>
            <h4 class="boldest text-center m-0 <%= @dark_mode ? 'white' : 'black' %>">Likes</h4>
            <div style="height: 25px; width: 32px;">
            </div>
          </div>
          <div class="post-likes-modal pt-3 <%= @dark_mode ? 'dark-mode' : 'normal-mode' %>">
            <% post.likes.each do |like| %>
              <%= link_to user_path(like.user), class: "no-decoration" do %>
                <div class="user-show-profile d-flex justify-content-center align-items-center mb-3">
                  <%= render 'users/user_avatar', user: like.user, classes: 'avatar-large default-avatar bold text-28' %>
                  <div class="user-show-profile-info user-all flex-grow-1 ml-2">
                    <h5 class="boldest m-0 <%= @dark_mode ? 'white' : 'black' %>"><%= like.user.user_username %></h5>
                     <p class="m-0 <%= @dark_mode ? 'grey' : 'grey' %>"><%= like.user.full_name %></p>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>

      <!-- COMMENTS MODAL -->
      <!-- COMMENTS MODAL -->
      <!-- COMMENTS MODAL -->
      <!-- COMMENTS MODAL -->
      <!-- COMMENTS MODAL -->

      <div id="commentsOffcanvas<%= post.id %>" class="offcanvas offcanvas-bg" data-target="posts.offCanvas">
        <!-- OFFCANVAS UNDERLAY -->
        <div class="underlay" data-action="click->posts#hideOffcanvas" data-target="posts.underlay"></div>
        <!-- OFFCANVAS UNDERLAY -->
        <div class="offcanvas__container offcanvas__container-comments pb-0 offcanvas-bg">
          <div class="border-bottom pb-3 offcanvas-header offcanvas-header-comments">
            <div class="cursor-pointer" data-action="click->posts#hideOffcanvasFromX">
              <%= image_tag "#{ @dark_mode ? 'plus-white.png' : 'plus.png' }", width: 25, class: 'post-exit' %>
            </div>
            <h4 class="boldest text-center m-0 <%= @dark_mode ? 'grey' : 'black' %>">Comments</h4>
            <div style="height: 25px; width: 32px;">
            </div>
          </div>
          <div class="modal-content comments-modal">
            <div class="modal-body post-comments-body d-flex p-0">
              <% if post.photo.content_type.split("/")[0] == "image" %>
                <%= cl_image_tag post.photo.key, format: :jpg, class: 'post-modal-image' %>
              <% elsif post.photo.content_type.split("/")[0] == "video" %>
                <%= cl_video_tag post.photo.key, controls: true, quality: :auto, class: 'post-modal-image post-video' %>
              <% end %>
              <div class="modal-comments <%= @dark_mode ? 'dark-mode' : 'normal-mode' %>">
                <div class="post-comments modal-post-comments post-modal-comments-box_<%= post.id %>" data-target="posts.commentsBox">
                  <% if post.caption.present? %>
                    <div class="post-card-user-info boldest py-2 border-bottom">
                      <% if post.user.avatar.attached?  %>
                        <%= cl_image_tag post.user.avatar.key, format: :jpg, width: 40, class: 'avatar-sm' %>
                      <% else %>
                        <%= render 'users/user_avatar', user: post.user, classes: 'avatar-sm default-avatar' %>
                      <% end %>
                      <%= link_to user_path(post.user), class: 'no-decoration' do %>
                        <span class="m-0 link-hover <%= @dark_mode ? 'white' : 'black' %>"><%= post.user.user_username %></span> <span class="s-medium-text <%= @dark_mode ? 'white' : 'black' %>" style="font-weight: 200;"><%= post.caption %></span>
                      <% end %>
                    </div>
                  <% end %>
                  <% post.comments.each do |comment| %>
                    <%= render 'modal_comment', comment: comment %>
                  <% end %>
                </div>
                <div class="modal-footer p-0">
                  <%= simple_form_for [post, @comment], remote: true, data: { action: "ajax:success->posts#newCommentModal", id: "#{post.id}" }, html: { class: "w-100 m-0" } do |f| %>
                    <%= f.input :content,
                                required: true,
                                label: false,
                                placeholder: 'Add a comment...',
                                input_html: { class: "post-card-form-input all-comments-input #{ @dark_mode ? 'dark-mode border-grey white' : 'normal-mode' }", data: { action: "keyup->posts#postModalButton" } } %>
                    <%= f.hidden_field :modal, :value => 'true' %>
                    <%= f.submit 'Post', class: "post-card-form-button all-comments-button #{ @dark_mode ? 'dark-mode border-grey grey' : 'normal-mode' }", data: { target: 'posts.button' } %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_dark_mode_link_pwa.html.erb
<div class="pwa-navbar-section">
  <div class="d-flex align-items-center flex-grow-1">
    <span class="white mr-1 tiny-text">L</span>
    <%= link_to toggle_dark_mode_path(dark_mode: false), remote: true, data: { action: "ajax:success->common#toggleDarkModePwa" } do %>
      <div class="switch <%= 'switch-dark' if @dark_mode %>" data-target="common.switchPwa">
        <div class="toggle toggle-dark"></div>
      </div>
    <% end %>
    <span class="white ml-1 tiny-text">D</span>
  </div>
</div>

app/views/shared/_pwa_navbar.html.erb
<div class="pwa-navbar-container">
  <div class="pwa-navbar-spacer" data-target="navbar.pwaNavbarSpacer"></div>
  <div class="pwa-navbar" data-target="navbar.pwaNavbar">
    <%= link_to posts_path, class: "pwa-navbar-section no-decoration", data: { action: 'click->common#showLoader' } do %>
      <div class="pwa-navbar-section">
        <% if params[:controller] == 'posts' %>
          <%= image_tag 'posts-lime.png', class: 'pwa-navbar-icon' %>
        <% else %>
          <%= image_tag 'posts.png', class: 'pwa-navbar-icon' %>
        <% end %>
      </div>
    <% end %>
<!--     <%#= link_to tips_path, class: "pwa-navbar-section no-decoration", data: { action: 'click->common#showLoader' } do %>
      <div class="pwa-navbar-section">
        <%# if params[:controller] == 'tips' %>
          <%#= image_tag 'careers-blue.png', class: 'pwa-navbar-icon' %>
        <%# else %>
          <%#= image_tag 'careers.png', class: 'pwa-navbar-icon' %>
        <%# end %>
      </div>
    <%# end %>
    <%#= link_to resources_path, class: 'pwa-navbar-section no-decoration', data: { action: 'click->common#showLoader' } do %>
      <div class="pwa-navbar-section">
        <%# if params[:controller] == 'resources' %>
          <%#= image_tag 'resources-blue.png', class: 'pwa-navbar-icon' %>
        <%# else %>
          <%#= image_tag 'resources.png', class: 'pwa-navbar-icon' %>
        <%# end %>
      </div>
    <%# end %>
    <%#= link_to articles_path, class: 'pwa-navbar-section no-decoration', data: { action: 'click->common#showLoader' } do %>
      <div class="pwa-navbar-section">
        <%# if params[:controller] == 'articles' %>
          <%#= image_tag 'articles-blue.png', class: 'pwa-navbar-icon' %>
        <%# else %>
          <%#= image_tag 'articles.png', class: 'pwa-navbar-icon' %>
        <%# end %>
      </div>
    <%# end %> -->

    <%= link_to no_user_path, class: 'pwa-navbar-section no-decoration', data: { action: 'click->common#showLoader' } do %>
      <div class="pwa-navbar-section">
        <!-- CONDITION BELOW - OR HOME PAGE FOR LOGGED IN USERS -->
        <% if params[:controller] == 'users' && params[:action] == 'show' %>
          <%= image_tag 'user-lime.png', class: 'pwa-navbar-icon' %>
        <% else %>
          <%= image_tag 'user-white.png', class: 'pwa-navbar-icon' %>
        <% end %>
      </div>
    <% end %>
    <%= link_to info_path, class: 'pwa-navbar-section no-decoration', data: { action: 'click->common#showLoader' } do %>
      <li class="pwa-navbar-section">
        <% if params[:controller] == 'pages' && params[:action] == 'info' %>
          <%= image_tag 'info-lime.png', class: 'pwa-navbar-icon' %>
        <% else %>
          <%= image_tag 'info-white.png', class: 'pwa-navbar-icon' %>
        <% end %>
      </li>
    <% end %>
    <%= render 'shared/dark_mode_link_pwa' %>
  </div>
</div>